/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

 

Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
*/


class Solution {
public:
    char findTheDifference(string s, string t) {
        int hash_s[26] = {};
        int hash_t[26] = {};
        for(int i = 0; i < t.size()-1; ++i)
        {
            hash_s[s[i] - 'a']++;
            hash_t[t[i] - 'a']++;
        }
        hash_t[t[t.size()-1] - 'a']++;


        for(int i = 0; i < 26; ++i)
        {
            if(hash_s[i] != hash_t[i]) return i + 'a';
        }


        throw "WTF";
    }
};
